rvm:
  - 2.2.3
services:
  - postgresql
before_script:
  - psql -c 'create database workshops_development;' -U postgres
  - cp config/database.yml.travis config/database.yml
addons:
  postgresql: '9.3'